version: '3.4'
configs:
  AlertmanagerB:
    file: ./config/alertmanager/alertmanager.yml
  Srv_0B:
    file: ./config/prometheus/alertRules/srv_0.yml
  Fping_0B:
    file: ./config/prometheus/alertRules/fping_0.yml
  PrometheusB:
    file: ./config/prometheus/prometheusB.yml
  Prometheus_WebB:
    file: ./config/prometheus/web-config.yml
networks:
  stacks_observability:
    external:
      name: stacks_observability
services:
  prometheusB:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/etc/prometheus/console_libraries
    - --web.console.templates=/etc/prometheus/consoles
    - --storage.tsdb.retention.time=24h
    - --web.enable-lifecycle
    configs:
    - source: PrometheusB
      target: /etc/prometheus/prometheus.yml
    - source: Prometheus_WebB
      target: /path/to/web-config.yml
    deploy:
      placement:
        constraints:
        - node.hostname == docker-3
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    image: prom/prometheus
    networks:
      - stacks_observability
    ports:
    - published: 9092
      target: 9090
    volumes:
    - prometheus_B:/prometheus:rw

  blackboxB:
    deploy:
      placement:
        constraints:
        - node.hostname == docker-3
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    image: prom/blackbox-exporter
    networks:
      - stacks_observability

  fpingB:
    deploy:
      placement:
        constraints:
        - node.hostname == docker-3
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    image: bbrks/fping-exporter:latest
    networks:
      - stacks_observability

  alertmanagerB:
    command:
    - --config.file=/etc/alertmanager/alertmanager.yml
    - --storage.path=/alertmanager
    configs:
    - source: AlertmanagerB
      target: /etc/alertmanager/alertmanager.yml
    deploy:
      placement:
        constraints:
        - node.hostname == docker-3
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        delay: 10s
        parallelism: 2
    environment:
      TZ: America/Belem
    image: prom/alertmanager
    networks:
      - stacks_observability
    ports:
    - published: 9293
      target: 9093


volumes:
  prometheus_B: {}
