global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    __replica__: promscale_deploy_ha-promscale-connector
    cluster: monitoring-cluster

scrape_configs:

remote_write:
    - url: "http://promscale:9201/write"
remote_read:
    - url: "http://promscale:9201/read"